version: '3.1'
services:
    app:
        build: .
        volumes:
            - ./scrape:/app

    db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            PGDATA: /tmp
        volumes:
            - ./scrape:/var/lib/postgresql/data/scrape
        depends_on:
            - app

#     adminer:
#         image: adminer
#         restart: always  
#         depends_on: 
#             - db      
#         ports:
#             - 8080:8080

          
        
