version: '3.1'
services:
    # app:
    #     build: .
    #     volumes:
    #         - $PWD/scrape:/app

    db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - $PWD/db:/var/lib/postgresql/data
        # depends_on:
        #     - app
    
    adminer:
        image: adminer
        restart: always  
        depends_on: 
            - db      
        ports:
            - 8080:8080

              
        
